### ISSUE TITLE
Building for Windows?

### ISSUE THREAD

**Issue by marxo** [strawbrary/php-sha3#1]
Is it possible to compile this on Windows?

I know that this is an unpopular thing to ask, but I have a PHP 5.4 + Apache setup.

**Comment by strawbrary** [comment]
It looks like you put this in the wrong repo. This is for the sha3 extension. If you're still having the issue go ahead and open an issue in php-blake2 and please add the steps with how you're building on Windows as I have not tried this before and am not familiar with the build tools for Windows. Thanks.
