### ISSUE TITLE
How to use on web hotel?

### ISSUE THREAD

**Issue by OZ1SEJ** [strawbrary/php-sha3#18]
I can see that I need to git clone and then edit php.ini to use this. Where my web site is hosted, I don't have access to the php.ini file. Does that mean I can't use php-sha3?

**Comment by ghost** [comment]
This means you will not be able to use it. Assuming that you can not even insert own module binaries.
Maybe try pure PHP implementation? https://github.com/0xbb/php-sha3
I did not test this one myself but it came first in quick search.

**Comment by OZ1SEJ** [comment]
Wow - thank you!
