### ISSUE TITLE
Doesn't work sha3 in php.

### ISSUE THREAD

**Issue by hunterpl** [strawbrary/php-sha3#3]
Hello !

echo sha3(''); <--- doesn't work

if i did test on page .php

<?php
echo sha3('test');

Fatal error: Call to undefined function sha3() in /var/www/*****/password.php on line 2

Why it doesn't work ?

**Comment by strawbrary** [comment]
This means the extension isn't installed. Have you been sure to restart your httpd/FPM after running `make install`?
