### ISSUE TITLE
Different Results on Javascript And C

### ISSUE THREAD

**Issue by MicMonen** [strawbrary/php-sha3#8]
When I use Javascript or other sources to generate hashes it doesn't match with this extensions. It does match with eachother, any clues how this can be?

**Comment by strawbrary** [comment]
SHA-3/Keccak has been revised a few times so my guess would be that they are using different versions of the standard than this extension. If you provide links to the projects you are using and some example input I can investigate.

**Comment by MicMonen** [comment]
HI strawbrary, thanks for your answer!

If you google "sha 3 generator" you have a bunch of sites that generates a different hash. Most of them use the much used Crypto-js library in javascript. Also I downloaded the rhash library on ubuntu and it also had a different hash.

In the end it seems they all used an older technique and I thought you where outdated but it was the other way around, sorry for that.
