### ISSUE TITLE
make && make install error

### ISSUE THREAD

**Issue by 820744** [strawbrary/php-sha3#9]
<pre>
<i>root@R13L:~/php-sha3# make && make install</i>
/bin/bash /root/php-sha3/libtool --mode=compile cc  -I. -I/root/php-sha3 -DPHP_ATOM_INC -I/root/php-sha3/include -I/root/php-sha3/main -I/root/php-sha3 -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php-sha3/php_sha3.c -o php_sha3.lo 
libtool: compile:  cc -I. -I/root/php-sha3 -DPHP_ATOM_INC -I/root/php-sha3/include -I/root/php-sha3/main -I/root/php-sha3 -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php-sha3/php_sha3.c  -fPIC -DPIC -o .libs/php_sha3.o
/root/php-sha3/php_sha3.c: In function ‘zif_sha3’:
<b>/root/php-sha3/php_sha3.c:80:58: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
         RETURN_STRINGL((char *)hashVal, hashByteLength, 1);</b>
                                                          ^
<b>/root/php-sha3/php_sha3.c:80:9: error: ‘RETURN_STRINGL’ undeclared (first use in this function)
         RETURN_STRINGL((char *)hashVal, hashByteLength, 1);</b>
         ^
/root/php-sha3/php_sha3.c:80:9: note: each undeclared identifier is reported only once for each function it appears in
<b>/root/php-sha3/php_sha3.c:87:56: error: macro "RETURN_STRINGL" passed 3 arguments, but takes just 2
         RETURN_STRINGL(hexDigest, hashByteLength * 2, 1);</b>
                                                        ^
Makefile:193: recipe for target 'php_sha3.lo' failed
make: *** [php_sha3.lo] Error 1
</pre>

> Ubuntu 15.10
> Nginx 1.9.x
> PHP 7.0

**Comment by strawbrary** [comment]
I haven't yet had the time to upgrade this extension to support PHP 7 unfortunately.

**Comment by strawbrary** [comment]
Fixed by #11. Give it a try now!
